Addition of report function
dojot-ifg/gui-v2 pull request #1
Opened 2021-01-11 10:22 UTC by cfrancisco

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2021-01-12 15:27 UTC, luisfelipefurlan requested changes

2021-01-12 15:27 UTC, luisfelipefurlan commented on src/js/common/services/device.service.js
> +  console.log('getDevicesHistoryParsed', filter);
Tirar o console.log

2021-01-12 15:27 UTC, luisfelipefurlan commented on src/js/views/dashboard/View.jsx
> +          <ReportFilter t={t} />
O ReportFilter tem que estar fora do DevelopmentContainer
Tudo que estiver dentro do DevelopmentContainer não vai aparecer na build de produção

2021-01-12 15:27 UTC, luisfelipefurlan commented on src/js/views/dashboard/report/index.jsx
> +        console.log('campusDict', campusDict);
Remover o console.log

2021-01-12 15:27 UTC, luisfelipefurlan commented on src/js/views/dashboard/report/index.jsx
> +        console.log('getCsvCampus', response);
Remover o console.log

2021-01-12 16:35 UTC, cfrancisco commented on src/js/views/dashboard/View.jsx
> +          <ReportFilter t={t} />
Olha só, bom saber disso!

2021-01-19 11:46 UTC, luisfelipefurlan approved these changes

2021-01-19 11:49 UTC, merged